name: data730
channels:
  - conda-forge
  - chuckpr
dependencies:
  - python = 3.9
  - r-tidymodels
  - r-tidyverse
  - r-irkernel
  - r-palmerpenguins
  - r-islr2
  - r-moderndive
  - scikit-learn
  - patsy
  - pyarrow
  - plotnine
  - statsmodels
  - altair
  - ipykernel
  - pip
  - pip:
      - palmerpenguins
